### ISSUE TITLE
Force root wrapping per class

### ISSUE THREAD

**Issue by chrylis** [FasterXML/jackson-annotations#33] opened 2014-05-07 09:09 UTC
I'm working on mapping an external service that sends postbacks in wrapped JSON. I have set the `@JsonRootName` on the class and can read objects with a specially-configured mapper, but this wrapping behavior belongs to this service (i.e., a certain set of classes) specifically, and not to the overall system (Spring MVC, which expects a single mapping configuration).

Since it's known that this class will always need to be unwrapped, and request classes wrapped, it would be much clearer to be able to force root wrapping per class, perhaps with an `alwaysWrap` field on the `@JsonRootName` annotation. Is this a feasible feature?

**Comment by cowtowncoder** [comment] 2015-04-02 18:35
Note: was not included in 2.5.

**Comment by olivergierke** [comment] 2015-11-06 13:51
You might wanna clean up the JavaDoc on [`@JsonRootName`](https://github.com/FasterXML/jackson-annotations/blob/master/src/main/java/com/fasterxml/jackson/annotation/JsonRootName.java) accordingly as it still indicate the functionality might be (or better: have been, which it hasn't) introduced in 2.5.

Other than that, +1 for adding this :).

**Comment by jbm4sa** [comment] 2015-11-26 10:25
Is there a plan to include this one in near future? We are quite depending on it, so we need to plan at least :)

**Comment by cowtowncoder** [comment] 2015-11-26 17:34
@jbm4sa No one working actively on this that I am aware of. Contributions welcome. But I will move this to `jackson-databind` as it is implement there, even if a tiny part may be relevant here; issues reported here are easier to ignore as well.

**Comment by cowtowncoder** [comment] 2015-11-26 17:36
Moved to https://github.com/FasterXML/jackson-databind/issues/1022

**Comment by mv07517** [comment] 2016-03-02 05:13
Is there any way to remove default root wrapping? I want to send json without root element and I am not giving  @JsonRootName still its wrapping with class name? Please suggest something. @chrylis  @cowtowncoder

**Comment by cowtowncoder** [comment] 2016-03-04 18:11
@mv07517 Couple of ways. `ObjectWriter` has `withoutRootName()` method that can be used to do this for specific calls. Or, you may sub-class `JacksonAnnotationIntrospector` to sort of hide the annotation.

As to why root wrapping seems to be enabled in your case, I do not know. For questions, please use the mailing list in future; or, if you do have what you think is a bug, file a new issue with reproduction. Tagging questions to existing issues tends to make discussions more convoluted and harder to read.

**Comment by OndraZizka** [comment] 2019-06-10 05:13
Any progress on this? I am looking at `JacksonAnnotationIntrospector` but see no way to do this. `findRootName()` doesn't affect this behavior.

**Comment by cxl-todd** [comment] 2020-09-09 23:16
Seems like this is still commented out. Any thoughts on reintroducing this functionality? Would be great to do on a per-class basis rather than affecting the entire object mapper.

**Comment by cowtowncoder** [comment] 2020-09-10 02:01
@cxl-todd Unfortunately support was never implemented, even though annotation declaration was accidentally released.
If someone has time to look into this, I could help. But last I checked it seemed difficult to achieve. Esp. compared to relative ease with which one can just wrap root object in a simple Map to achieve the same effect.

**Comment by malloc32** [comment] 2020-10-23 12:03
I need this functionally to, I need that object mapper only wrap root when class has the annotation. Any advance?
Thank you.

**Comment by cowtowncoder** [comment] 2020-10-23 16:16
@malloc32 for help with usage etc, mailing lists would be the place to ask, not issue. I can't think of anything simple that would do this automatically just based on annotation.

**Comment by cowtowncoder** [comment] 2024-11-06 22:20
Moved to https://github.com/FasterXML/jackson-databind/issues/1022, closing.

**Closed by cowtowncoder** 2024-11-06 22:20 UTC
