### ISSUE TITLE
@JsonFormat formatted date data appear time zone problem

### ISSUE THREAD

**Issue by guoai2015** [FasterXML/jackson-annotations#93] opened 2016-06-13 07:46 UTC
DOC is said to default on the use of TimeZone.getDefault (), but the actual is not the case. Before it is written directly on the fixed value. But now the project needs to be internationalized and deployed to different countries, so the time zone must take the time to run the environment. However, with the JSON @JsonFormat into the string after the time and running environment of the default time zone for a long time.

**Comment by cowtowncoder** [comment] 2016-06-13 21:07
I am sorry but I do not understand the description of the problem.

**Comment by cowtowncoder** [comment] 2016-06-13 22:53
Duplicate of https://github.com/FasterXML/jackson-databind/issues/1266.
Please only enter bug once, or if it needs to be moved, close all but one of duplicates.

**Closed by cowtowncoder** 2016-06-13 22:53 UTC
